spring:
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
    datasource:
        driverClassName: org.postgresql.Driver
# locally
        url: jdbc:postgresql://localhost/atpfx
# heroku:
#        url: jdbc:postgresql://ec2-23-23-215-150.compute-1.amazonaws.com:5432/de5ep4rol5uj29
#        username: pnlflomjvojlcg
#        password: eaBetviusZre9ql1htfK9zECow
    dao:
      exceptiontranslation:
        enabled: true

logging.level: INFO

# this is configured as an environment variable by heroku
server:
    port: ${port:7777}

# app specific properties
# fxcm providers
fxcm:
  username: D172817499001
  password: 4414
  user.session.pin: 111111

# should be configured as an env. variable
#proxy:
local.proxy.host: localhost
local.proxy.port: 3128


---

spring:
  profiles: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:notification

  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
