package com.atpfx.model;

public enum Pair {

    EUR_USD, USD_JPY, GBP_USD, USD_CHF, EUR_CHF, AUD_USD, USD_CAD, NZD_USD, EUR_GBP, EUR_JPY, GBP_JPY, CHF_JPY, GBP_CHF, EUR_AUD,
    EUR_CAD, AUD_CAD, AUD_JPY, CAD_JPY, NZD_JPY, GBP_CAD, GBP_NZD, GBP_AUD, AUD_NZD, AUD_CHF, EUR_NZD, USD_ZAR, USD_SGD, USD_HKD,
    USD_TRY, EUR_TRY

}
